### ISSUE TITLE
Vite plugin inserting lines at the wrong place

### ISSUE THREAD

**Issue by WarningImHack3r** [inlang/inlang#687]
## Problem

My problem is related to this line:
```svelte
{#if $language}
```
trying to get inserted on top of my `+layout.svelte`. The problem is that I'm using a:
```svelte
<svelte:window bind:... />
```
binding on top of my `+layout.svelte` and this leads to an error stating that this special element cannot be wrapped into an `if` statement (which makes sense).

### Expected behavior

Insert the plugin's lines *below*  any Svelte special element

## Steps to reproduce

1. Create a `.svelte` file (presumably any kind of non-component Svelte file)
2. Add a `<svelte:...` line on top of any HTML code
3. Configure the Inlang Vite plugin
4. `npm run dev`

**Comment by ivanhofer** [comment]
Thanks, we will take alook at this issue soon

**Comment by benjaminpreiss** [comment]
Thanks for submitting this issue. I checked in the docs and as far as I can tell the following tags HAVE to be placed at a top level and can therefore not be wrapped:

- `<svelte:window>`: https://svelte.dev/docs#template-syntax-svelte-window
- `<svelte:document>`: https://svelte.dev/docs#template-syntax-svelte-document
- `<svelte:body>`: https://svelte.dev/docs#template-syntax-svelte-body
- `<svelte:head>`: https://svelte.dev/docs#template-syntax-svelte-head

@ivanhofer Pls confirm

**Comment by ivanhofer** [comment]
`<svelte:options>` https://svelte.dev/docs#template-syntax-svelte-options probably also need to be at the root

**Comment by benjaminpreiss** [comment]
I guess I can safely move these elements around amongst the other root elements? Means, the place at which these tags appear doesn't matter as long as they appear in the root?

**Comment by ivanhofer** [comment]
Yes, I think so, but we could also keep the order of them intact

**Comment by ivanhofer** [comment]
fixed in version  `0.3.0`

**Comment by TazorDE** [comment]
Using @inlang/sdk-js version 0.6.1 the issue appears to still exist. I'm not sure exactly why but when I'm placing a `<svelte:head>` component in my `routes/+layout.svelte` the following error is thrown: 
```
Internal server error: /src/routes/+layout.svelte:61:15 <svelte:head> tags cannot be inside elements or blocks
  Plugin: vite-plugin-svelte
  File: /src/routes/+layout.svelte:61:15
   59 |    }
   60 |  </script>
   61 |  {#if $language}<svelte:head />
                        ^
   62 |  
   63 |   (x5)
```
This only happens in the `routes/+layout.svelte` file, from my limited testing other `+layout.svelte` files are fine. Please note that while the vite-plugin-svelte throws the error, the error arises due to inlang wrapping the markup body of `routes/+layout.svelte`

Reproduction steps:

1. Create a new (Skeleton-)SvelteKit project
2. Set up Inlang following the documentation
3. In the routes/+layout.svelte implement a `<svelte:head>` -component
4. try to run the project

Specifically I try to implement the [Lightswitch component](https://www.skeleton.dev/utilities/lightswitches) Skeleton offers. However if I include this component another issue arises, I'm not sure yet if it is related to this issue. I'll try to deduce that once this is working again. 

My `routes/+layout.svelte` for reference:
```html
<script lang="ts">
	// The ordering of these imports is critical to your app working properly
	import '../theme.postcss';
	// If you have source.organizeImports set to true in VSCode, then it will auto change this ordering
	import '@skeletonlabs/skeleton/styles/skeleton.css';
	// Most of your app wide CSS should be put in this file
	import '../app.postcss';
	import { AppShell, AppBar, LightSwitch, autoModeWatcher } from '@skeletonlabs/skeleton';
	import { onMount } from 'svelte';
	import LoginButton from '$lib/LoginButton.svelte';
	import { i } from '@inlang/sdk-js';
</script>

<svelte:head>{@html `<script>${autoModeWatcher.toString()} autoModeWatcher();</script>`}</svelte:head>

<!-- ... rest of markup ... -->
```

**Comment by ivanhofer** [comment]
Thanks for sharing the example. We are currently refactoring our core logic and the issue will be adressed there. As a workaround you can just move all your coude into a new component and render it in `+layout.svelte`.

_+layout.svelte_
```svelte
<script lang="ts">
	import Layout.svelte
</script>

<Layout />
```
_Layout.svelte_
```svelte
<script lang="ts">
	// The ordering of these imports is critical to your app working properly
	import '../theme.postcss';
	// If you have source.organizeImports set to true in VSCode, then it will auto change this ordering
	import '@skeletonlabs/skeleton/styles/skeleton.css';
	// Most of your app wide CSS should be put in this file
	import '../app.postcss';
	import { AppShell, AppBar, LightSwitch, autoModeWatcher } from '@skeletonlabs/skeleton';
	import { onMount } from 'svelte';
	import LoginButton from '$lib/LoginButton.svelte';
	import { i } from '@inlang/sdk-js';
</script>

<svelte:head>{@html `<script>${autoModeWatcher.toString()} autoModeWatcher();</script>`}</svelte:head>

<!-- ... remainder of markup ... -->
```

**Comment by jannesblobel** [comment]
Unfortunately, Ivan has passed away, and we are trying to find a solution. 
 I will close this issue as not  planned for now when we have a solution.
