### ISSUE TITLE
Conflict between graphql houdini and inlang

### ISSUE THREAD

**Issue by dalton5** [inlang/inlang#878]
Hi,

Hi. I think there is a conflict between houdini and inlang. I have the error 

Internal server error: Transform failed with 2 errors:

`C:/Users/Alexis.m/Documents/GitHub/rental/rentalWebAppClient/client/src/routes/+layout.ts:18:13: ERROR: Multiple exports with the same name "load"
C:/Users/Alexis.m/Documents/GitHub/rental/rentalWebAppClient/client/src/routes/+layout.ts:18:13: ERROR: The symbol "load" has already been declared
  Plugin: vite:esbuild
  File: C:/Users/Alexis.m/Documents/GitHub/rental/rentalWebAppClient/client/src/routes/+layout.ts:18:1

  Multiple exports with the same name "load"
  16 |  }
  17 |
  18 |  export const load = initRootLayoutLoadWrapper({}).wrap(async (
     |               ^
  19 |      {
  20 |          url

  The symbol "load" has already been declared
  16 |  }
  17 |
  18 |  export const load = initRootLayoutLoadWrapper({}).wrap(async (
     |               ^
  19 |      {
  20 |          url`

ALso the detail of the issue:

`pluginCode: 'import { localStorageKey } from "@inlang/sdk-js/adapter-sveltekit/client/reactive";\r\n' +
    'import { initLocalStorageDetector, navigatorDetector } from "@inlang/sdk-js/detectors/client";\r\n' +
    'import { initRootLayoutLoadWrapper } from "@inlang/sdk-js/adapter-sveltekit/shared";\r\n' +
    'import { browser } from "$app/environment";\r\n' +
    'import { CommonStore, type Common$result } from "$houdini";\r\n' +
    'import { loadDataStrapi } from "$lib/api/strapiHelper";\r\n' +
    'import { commonStore } from "$lib/stores/dataStores";\r\n' +
    '\r\n' +
    'export async function load(event) {\r\n' +
    '    const __houdini__vite__plugin__return__value__ = {};\r\n' +
    '\r\n' +
    '    return {\r\n' +
    '        ...event.data,\r\n' +
    '        ...__houdini__vite__plugin__return__value__\r\n' +
    '    };\r\n' +
    '}\r\n' +
    '\r\n' +
    'export const load = initRootLayoutLoadWrapper({}).wrap(async (\r\n' +
    '    {\r\n' +
    '        url\r\n' +
    '    }\r\n' +
    ') => {\r\n' +
    '    const {\r\n' +
    '        pathname\r\n' +
    '    } = url;\r\n' +
    '\r\n' +
    '    const lang = ${pathname.match(/[^/]+?(?=\/|$)/) || ""};\r\n' +
    '    const route = pathname.replace(new RegExp(^/${lang}), "");\r\n' +
    '    await loadDataStrapi(event, new CommonStore(), commonStore);\r\n' +
    '\r\n' +
    '    return {\r\n' +
    '        stuff: {\r\n' +
    '            route,\r\n' +
    '            lang\r\n' +
    '        }\r\n' +
    '    };\r\n' +
    '});' `

**Comment by dalton5** [comment]
My layout.ts

`
import { CommonStore, type Common$result } from '$houdini';
import { loadDataStrapi } from '$lib/api/strapiHelper';
import { commonStore } from '$lib/stores/dataStores';

export const load = async ({ url }) => {

  const { pathname } = url;
  const lang = `${pathname.match(/[^/]+?(?=\/|$)/) || ''}`;
  const route = pathname.replace(new RegExp(`^/${lang}`), '');

  await loadDataStrapi(event, new CommonStore, commonStore);

  return { stuff: { route, lang } };
}
`

**Comment by ivanhofer** [comment]
@dalton5 please create a small repository which contains the issue, so we can investigate it.

**Comment by dalton5** [comment]
Thanks. When do you think it will be fixed please? Thanks

**Comment by ivanhofer** [comment]
The issue should be fixed in version `0.8.0`

**Comment by dalton5** [comment]
I use version 0.9.0 and I still have the same error:

Internal server error: Transform failed with 1 error:
*****/src/routes/+layout.ts:19:6: ERROR: The symbol "load" has already been declared
  Plugin: vite:esbuild
  File: *****/src/routes/+layout.ts:19:1

  The symbol "load" has already been declared
  17 |      };
  18 |  });
  19 |  const load = initLoadWrapper<LayoutLoad>().use(async (url, { params }, { i }) => {
     |        ^
  20 |      const { pathname } = url;
  21 |      const lang = `${pathname.match(/[^/]+?(?=\/|$)/) || ""}`;

      at failureErrorWithLog (*****node_modules\esbuild\lib\main.js:1646:15)
      at *****node_modules\esbuild\lib\main.js:847:29
      at responseCallbacks.<computed> (*****node_modules\esbuild\lib\main.js:703:9)
      at handleIncomingPacket (*****node_modules\esbuild\lib\main.js:762:9)
      at Socket.readFromStdout (*****node_modules\esbuild\lib\main.js:679:7)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
Error: Transform failed with 1 error:
*****/src/routes/+layout.ts:19:6: ERROR: The symbol "load" has already been declared
    at failureErrorWithLog (*****node_modules\esbuild\lib\main.js:1646:15)
    at *****node_modules\esbuild\lib\main.js:847:29
    at responseCallbacks.<computed> (*****node_modules\esbuild\lib\main.js:703:9)
    at handleIncomingPacket (*****node_modules\esbuild\lib\main.js:762:9)
    at Socket.readFromStdout (*****node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'The symbol "load" has already been declared'
    }
  ],
  warnings: [],
  frame: '\n' +
    '\x1B[33mThe symbol "load" has already been declared\x1B[39m\n' +
    '17 |      };\n' +
    '18 |  });\n' +
    '19 |  const load = initLoadWrapper<LayoutLoad>().use(async (url, { params }, { i }) => {\n' +
    '   |        ^\n' +
    '20 |      const { pathname } = url;\n' +
    '21 |      const lang = `${pathname.match(/[^/]+?(?=\\/|$)/) || ""}`;\n',
  loc: {
    file: '*****/src/routes/+layout.ts',
    line: 19,
    column: 1
  },
  plugin: 'vite:esbuild',
  id: '*****/src/routes/+layout.ts',
  pluginCode: "import { initLocalStorageDetector, navigatorDetector } from '@inlang/sdk-js/detectors/client';\n" +
    "import { browser } from '$app/environment';\n" +
    'import { CommonStore, type Common$result } from "$houdini";\n' +
    'import { loadDataStrapi } from "$lib/api/strapiHelper";\n' +
    'import { commonStore } from "$lib/stores/dataStores";\n' +
    'import { initLoadWrapper, initRootLayoutLoadWrapper } from "@inlang/sdk-js/adapter-sveltekit/shared";\n' +
    'import type { LayoutLoad } from "./$types";\n' +
    'export const load = initRootLayoutLoadWrapper({\n' +
    '    initDetectors: browser\n' +
    '        ? () => [initLocalStorageDetector(), navigatorDetector]\n' +
    '        : undefined\n' +
    '}).use(async function load(event) {\n' +
    '    const __houdini__vite__plugin__return__value__ = {};\n' +
    '    return {\n' +
    '        ...event.data,\n' +
    '        ...__houdini__vite__plugin__return__value__\n' +
    '    };\n' +
    '});\n' +
    'const load = initLoadWrapper<LayoutLoad>().use(async (url, { params }, { i }) => {\n' +
    '    const { pathname } = url;\n' +
    '    const lang = `${pathname.match(/[^/]+?(?=\\/|$)/) || ""}`;\n' +
    '    const route = pathname.replace(new RegExp(`^/${lang}`), "");\n' +
    '    await loadDataStrapi(language, referenceLanguage, event, new CommonStore(), commonStore);\n' +
    '    return {\n' +
    '        stuff: {\n' +
    '            route,\n' +
    '            lang\n' +
    '        }\n' +
    '    };\n' +
    '});'
}

**Comment by ivanhofer** [comment]
Can you please send me the contents of your file?

**Comment by dalton5** [comment]
`  import { CommonStore, type Common$result } from '$houdini';
import { loadDataStrapi } from '$lib/api/strapiHelper';
import { commonStore } from '$lib/stores/dataStores';
import { initLoadWrapper } from '@inlang/sdk-js/adapter-sveltekit/shared';
import type { LayoutLoad } from './$types';
//import { loadTranslations } from '$lib/translations';
  
/* @type { import('./$houdini').PageLoad } */
   const load = initLoadWrapper<LayoutLoad>()
	.use(async (url, { params }, { i }) => {

    const { pathname } = url;
    const lang = `${pathname.match(/[^/]+?(?=\/|$)/) || ''}`;
    const route = pathname.replace(new RegExp(`^/${lang}`), '');
   // await loadTranslations(lang, route);

    await loadDataStrapi(language, referenceLanguage, event, new CommonStore, commonStore);

    return { stuff: { route, lang } };
  })`

**Comment by ivanhofer** [comment]
If you want to manually setup inlang for that file, you need to also include the following import somewhere in that file: `import '@inlang/sdk-js/no-transforms'` as described [here](https://inlang.com/documentation/sdk/sveltekit/advanced).

**Comment by dalton5** [comment]
Ok thanks. But it doesn't fix the issue. 

I still have the error: ERROR: Multiple exports with the same name "load"

**Comment by ivanhofer** [comment]
Could you please create a repository where we can reproduce this error?

**Comment by ivanhofer** [comment]
This is probably an issue with `houdini` because the `SDK` will not alter the code if you include the correct import.

**Comment by dalton5** [comment]
> Could you please create a repository where we can reproduce this error?

Created the repo: https://github.com/dalton5/proofError

**Comment by ivanhofer** [comment]
As I already mentioned above, this is an issue in `houdini`. Please open an issue in their repo.
You can change the order of both vite plugins and it should work:
```diff
-plugins: [inlangPlugin(), houdini(), sveltekit()]
+plugins: [houdini(), inlangPlugin(), sveltekit()]
```
