### ISSUE TITLE
Extension fails to open config

### ISSUE THREAD

**Issue by LongarMD** [inlang/inlang#904]
## Problem
The path to the config is prefixed with `C:`, even though the project is on another drive.
![image](https://github.com/inlang/inlang/assets/21366959/d89d31b4-5629-4a7f-b7e6-d80d78d7e59d)
The path after d: is correct.
### Expected behavior
The config should load 😄 
## Steps to reproduce

1. Create the project on a non-main drive (not sure if related -- I initialized the project with SkeletonUI)
2. Install the extension

**Comment by samuelstroschein** [comment]
Thank you for filing the bug! I assigned @felixhaeberle who is the lead of the ide extension at the moment.

**Comment by felixhaeberle** [comment]
@LongarMD I have to debug it out with an external USB stick or something because I'm on a Mac and therefore I don't have more than one hard drives or even not virtualized ones. 😅 
Probably something a Windows user could help with @NiklasBuchfink

**Comment by felixhaeberle** [comment]
@NiklasBuchfink I can't reproduce this on Mac. Can you help me out?

**Comment by NiklasBuchfink** [comment]
I could not reproduce the error with my setup, so @felixhaeberle takes over the task again

**Comment by felixhaeberle** [comment]
@LongarMD We are still looking into your issue and hope to come up with a solution soon.

**Comment by felixhaeberle** [comment]
@LongarMD I think we fixed your problem! 🎉 Can you try again and see if it's working now. Reinstalling the IDE extension is also a good way to have the latest version we just released. If you are reading this just in the minute I'm writing this, please wait for 5 more minutes until VS Code has the extension updated in their system.

Feel free to reopen if the problem persists. ☺️

**Comment by LongarMD** [comment]
Hi! Thanks :) The error is now gone, but the extension still isn't working :/
Now I get this warning when I open a file (I'm assuming it's from InLang):
![image](https://github.com/inlang/inlang/assets/21366959/6fe06ac6-f589-4ea9-bf88-0142bbbd5840)

**Comment by LongarMD** [comment]
I uninstalled the extension and I'm still getting the warning, so it's probably not InLang 😄 But still, the extension's not working. It doesn't seem to be a project configuration issue because it works fine on my mac.

**Comment by felixhaeberle** [comment]
@LongarMD Okay, lets dig deeper and find out why this isn't working on Windows.

**Comment by felixhaeberle** [comment]
@samuelstroschein I can't reproduce this issue on Mac: I'll involve @NiklasBuchfink one last time to see if the extension is working for him or if he can reproduce the error. We need a more solid Windows testing strategy.

**Comment by LongarMD** [comment]
@felixhaeberle thanks! Let me know if there's anything I can do to help 😃

**Comment by felixhaeberle** [comment]
@LongarMD Can you provide me with your config?

**Comment by LongarMD** [comment]
Sure, here you go:
```
/**
 * @type { import("@inlang/core/config").DefineConfig }
 */
export async function defineConfig(env) {
	const { default: pluginYaml } = await env.$import(
		"https://cdn.jsdelivr.net/gh/felixhaeberle/inlang-plugin-yaml@2.0.1/dist/index.js"
	);
	const { default: sdkPlugin } = await env.$import(
		'https://cdn.jsdelivr.net/npm/@inlang/sdk-js-plugin@0.6.5/dist/index.js'
	);
	const { default: standardLintRules } = await env.$import(
		"https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js",
	);

	return {
		referenceLanguage: 'en',
		plugins: [
			sdkPlugin({
				languageNegotiation: {
					strategies: [{ type: 'url' }]
				}
			}),
			pluginYaml({
				pathPattern: './languages/{language}.yml'
			}),
			standardLintRules()
		]
	};
}
```

**Comment by LongarMD** [comment]
Also, this seems to be related to #933

**Comment by felixhaeberle** [comment]
@LongarMD Thank you very much, we will look into this issue with a Windows developer in our team early next week.

**Comment by felixhaeberle** [comment]
@LongarMD Could you share your output of `npx @inlang/cli config validate` with us? Does the config validate properly?

**Comment by LongarMD** [comment]
Yeah, the validation goes through fine
![image](https://github.com/inlang/inlang/assets/21366959/b8eb6323-6b9c-4421-a0ad-36996b060334)
